---
- name: Remove old docker images & containers
  docker_prune:
    images: yes
    containers: yes

- name: get code from GitHub
  git: 
    dest: /usr/local/src/reunhangout
    repo: https://github.com/mitmedialab/unhangout.git
    version: "{{django_repo_version}}"

- name: Build docker iamge
  docker_image:
    name: dirkcuys/unhangout
    build:
      path: /usr/local/src/reunhangout
      pull: yes
    tag: latest
    source: build
    force_source: yes
    state: present
